name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name:  Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0

      - name: Test and generate coverage
        run: yarn test:cov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}